spring:
  application:
    name: reactor
  hateoas:
    use-hal-as-default-json-media-type: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none