package com.relax.reactor.service.gamelogic.enumerated;

public enum AvalancheMode {
    REGENERATE("""
            When tiles explode, new tiles are generated by iterating through a for loop that selects replacement tiles 
            based on weighted probabilities defined in the game configuration
            """),
    CASCADE("""
            When tiles explode, new tiles come from the same reels, with the system taking the next tiles from 
            positions above the exploded ones.
            """),
    REROLL("""
            Similar to CASCADE, when tiles explode, new tiles come from randomly selected reels with random stop 
            positions, rather than following a predetermined sequence.
            """);

    private final String howItWorks;

    AvalancheMode(String howItWorks) {
        this.howItWorks = howItWorks;
    }
}
